openapi: 3.0.0
info:
  version: '1.0'
  title: American College of Rheumatology - ANA sub-serologies Testing
  description: >-
    A guideline object provides the evidence-based recommendation for Tests for
    anti-nuclear antibody (ANA) sub-serologies (including antibodies to
    double-stranded DNA, Smith, RNP, SSA, SSB, Scl-70, centromere) depending on
    the presence of a positive ANA and clinical suspicion of immune-mediated
    disease.
servers:
  - url: /99999/fk4b85k02x/1.0
paths:
  /getrecommendation:
    post:
      description: ANA sub-serologies Testing Recommendation.
      operationId: ana
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    input:
      required:
        - labtest
        - anatestresult
        - imdtestresult
      properties:
        labtest:
          type: string
          example: ana
        anatestresult:
          type: boolean
          example: true
        imdtestresult:
          type: boolean
          example: true
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: >-
            { 'test':true, 'status':'Positive ANA and clinical suspicion of
            immune-mediated disease', 'recs': [ ], 'source':'American College of
            Rheumatology',
            'link':'http://www.choosingwisely.org/clinician-lists/american-college-rheumatology-ana-sub-serologies-without-positive-ana-and-clinical-suspicion/'}
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
